package com.finfoundry.backend.mapper;

import com.finfoundry.backend.dto.inputDTO.CreateUserRequest;
import com.finfoundry.backend.dto.outputDTO.UserDTO;
import com.finfoundry.backend.model.User;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface UserMapper {
    UserDTO toUserDTO(User user);

    // Convert CreateUserRequest into a User entity.
    // Here, we don’t set id, createdAt, or updatedAt (these are generated by the DB)
    User fromCreateUserRequest(CreateUserRequest request);
}